version: "1.0"
info:
  model: int-scaffold
packages:
- name: FE_APR_04_ExternalProject
  gitServerName: RawaGit
  gitUrl: https://github.com/radhikaWarrierSAG/FE_APR_04_ExternalProject
  gitUsername: radhikaWarrierSAG
  gitBranch: main
services:
- serviceName: project.fe_apr_04_external.integrations:letmetrythedebug_01
  packages:
  - name: FE_APR_04_ExternalProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
